// <auto-generated />
using System;
using Klanata.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klanata.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkstationDbContext))]
    [Migration("20260717080822_V4PricingSafetyConstraints")]
    partial class V4PricingSafetyConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Klanata.Domain.Entities.AppMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppMetadata", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("SellerId", "MarketplaceId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.AuthorizationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeveloperApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedSecretReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperApplicationId");

                    b.HasIndex("EncryptedSecretReference")
                        .IsUnique();

                    b.ToTable("AuthorizationProfiles", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.DeveloperApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIdFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdFingerprint")
                        .IsUnique();

                    b.ToTable("DeveloperApplications", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanCreateDraftChangeSets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanReadCatalog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanReadListings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanReadPricing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanSimulatePricing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWriteMfnInventory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWritePrices")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MarketplaceParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WriteBlockReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceParticipationId")
                        .IsUnique();

                    b.ToTable("MarketplaceCapabilities", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSuspendedListings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsParticipating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SellerAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SellerAccountId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MarketplaceParticipations", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AmazonAcceptanceConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnomaliesReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingChangeSetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RuleVersionConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SellerMarketplaceConfirmed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PricingChangeSetId")
                        .IsUnique();

                    b.ToTable("PricingApprovals", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingChangeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingRuleSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationProfileId");

                    b.HasIndex("PricingRuleSetId");

                    b.HasIndex("PricingRunId")
                        .IsUnique();

                    b.ToTable("PricingChangeSets", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingChangeSetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BusinessPriceModified")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CurrentBusinessPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingChangeSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingRunItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TargetBusinessPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PricingRunItemId");

                    b.HasIndex("PricingChangeSetId", "PricingRunItemId")
                        .IsUnique();

                    b.ToTable("PricingChangeSetItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_PricingChangeSetItems_BusinessPriceUnchanged", "TargetBusinessPrice IS NULL AND BusinessPriceModified = 0");
                        });
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AbsoluteChangeCap")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("AtOrAboveThresholdType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AtOrAboveThresholdValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BelowThresholdType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BelowThresholdValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessPriceStrategy")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyPrecision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketplaceParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PercentageChangeCap")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationProfileId");

                    b.HasIndex("MarketplaceParticipationId");

                    b.HasIndex("SellerId", "MarketplaceId", "Version")
                        .IsUnique();

                    b.ToTable("PricingRuleSets", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketplaceParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingRuleSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationProfileId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MarketplaceParticipationId");

                    b.HasIndex("PricingRuleSetId");

                    b.HasIndex("RunNumber")
                        .IsUnique();

                    b.HasIndex("SellerId", "MarketplaceId", "CreatedAtUtc");

                    b.ToTable("PricingRuns", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentBusinessPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExclusionCodesData")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExclusionReasonsData")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PriceChange")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceChangePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PricingRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductListingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SynchronizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetBusinessPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductListingId");

                    b.HasIndex("PricingRunId", "Sku")
                        .IsUnique();

                    b.ToTable("PricingRunItems", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.ProductListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AmazonUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BusinessPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FulfillmentChannel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketplaceParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MfnQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SynchronizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SynchronizedUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceParticipationId");

                    b.HasIndex("SellerId", "MarketplaceId", "Sku")
                        .IsUnique();

                    b.HasIndex("SellerId", "MarketplaceId", "Status");

                    b.HasIndex("SellerId", "MarketplaceId", "SynchronizedUnixTimeSeconds");

                    b.ToTable("ProductListings", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.SellerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastDiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("SellerAccounts", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.SellerAuthorizationGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SellerAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationProfileId");

                    b.HasIndex("SellerAccountId")
                        .IsUnique()
                        .HasFilter("IsPrimary = 1");

                    b.HasIndex("SellerAccountId", "AuthorizationProfileId")
                        .IsUnique();

                    b.HasIndex("SellerAccountId", "Priority");

                    b.ToTable("SellerAuthorizationGrants", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.WorkerLease", b =>
                {
                    b.Property<string>("LeaseKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("HeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaseKey");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("WorkerLeases", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.AuthorizationProfile", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.DeveloperApplication", null)
                        .WithMany()
                        .HasForeignKey("DeveloperApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceCapability", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.MarketplaceParticipation", null)
                        .WithOne()
                        .HasForeignKey("Klanata.Domain.Entities.MarketplaceCapability", "MarketplaceParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceParticipation", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.SellerAccount", null)
                        .WithMany()
                        .HasForeignKey("SellerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingApproval", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.PricingChangeSet", null)
                        .WithMany()
                        .HasForeignKey("PricingChangeSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingChangeSet", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.AuthorizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.PricingRuleSet", null)
                        .WithMany()
                        .HasForeignKey("PricingRuleSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.PricingRun", null)
                        .WithMany()
                        .HasForeignKey("PricingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingChangeSetItem", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.PricingChangeSet", null)
                        .WithMany()
                        .HasForeignKey("PricingChangeSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.PricingRunItem", null)
                        .WithMany()
                        .HasForeignKey("PricingRunItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingRuleSet", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.AuthorizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.MarketplaceParticipation", null)
                        .WithMany()
                        .HasForeignKey("MarketplaceParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingRun", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.AuthorizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.MarketplaceParticipation", null)
                        .WithMany()
                        .HasForeignKey("MarketplaceParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.PricingRuleSet", null)
                        .WithMany()
                        .HasForeignKey("PricingRuleSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.PricingRunItem", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.PricingRun", null)
                        .WithMany()
                        .HasForeignKey("PricingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.ProductListing", null)
                        .WithMany()
                        .HasForeignKey("ProductListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.ProductListing", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.MarketplaceParticipation", null)
                        .WithMany()
                        .HasForeignKey("MarketplaceParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.SellerAuthorizationGrant", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.AuthorizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Klanata.Domain.Entities.SellerAccount", null)
                        .WithMany()
                        .HasForeignKey("SellerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
