// <auto-generated />
using System;
using Klanata.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klanata.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkstationDbContext))]
    [Migration("20260716071915_V3CommerceContextReadModel")]
    partial class V3CommerceContextReadModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Klanata.Domain.Entities.AppMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppMetadata", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("SellerId", "MarketplaceId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.AuthorizationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeveloperApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedSecretReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperApplicationId");

                    b.HasIndex("EncryptedSecretReference")
                        .IsUnique();

                    b.ToTable("AuthorizationProfiles", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.DeveloperApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIdFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdFingerprint")
                        .IsUnique();

                    b.ToTable("DeveloperApplications", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanCreateDraftChangeSets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanReadCatalog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanReadListings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanReadPricing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanSimulatePricing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWriteMfnInventory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWritePrices")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MarketplaceParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WriteBlockReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceParticipationId")
                        .IsUnique();

                    b.ToTable("MarketplaceCapabilities", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSuspendedListings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsParticipating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SellerAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SellerAccountId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MarketplaceParticipations", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.ProductListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AmazonUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BusinessPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FulfillmentChannel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketplaceParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MfnQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SynchronizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SynchronizedUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceParticipationId");

                    b.HasIndex("SellerId", "MarketplaceId", "Sku")
                        .IsUnique();

                    b.HasIndex("SellerId", "MarketplaceId", "Status");

                    b.HasIndex("SellerId", "MarketplaceId", "SynchronizedUnixTimeSeconds");

                    b.ToTable("ProductListings", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.SellerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastDiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationProfileId");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("SellerAccounts", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.WorkerLease", b =>
                {
                    b.Property<string>("LeaseKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("HeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaseKey");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("WorkerLeases", (string)null);
                });

            modelBuilder.Entity("Klanata.Domain.Entities.AuthorizationProfile", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.DeveloperApplication", null)
                        .WithMany()
                        .HasForeignKey("DeveloperApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceCapability", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.MarketplaceParticipation", null)
                        .WithOne()
                        .HasForeignKey("Klanata.Domain.Entities.MarketplaceCapability", "MarketplaceParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.MarketplaceParticipation", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.SellerAccount", null)
                        .WithMany()
                        .HasForeignKey("SellerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.ProductListing", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.MarketplaceParticipation", null)
                        .WithMany()
                        .HasForeignKey("MarketplaceParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Klanata.Domain.Entities.SellerAccount", b =>
                {
                    b.HasOne("Klanata.Domain.Entities.AuthorizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
